### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by dustinspecker** [albenesi/calledIt#7]
Can you add `calledit` to Travis CI? I'm unable to without having admin rights on the repo. I *think* you can add me as an admin if you want me to setup Travis.

**Comment by albenesi** [comment]
Looked for admin rights and couldn't find it.
I think I added it to Travis CI. Is there anything more I need to do? Will you be able to access it?

**Comment by dustinspecker** [comment]
Looks good. Thanks.

**Comment by albenesi** [comment]
Great. I think I could transfer this repo to an organization in the future, too, if that would help.
